export default function Terms() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 leading-relaxed text-slate-700">
      <h1 className="text-2xl font-semibold text-slate-900">Terms of Service</h1>
      <p className="mt-4">SB AI Systems Social Agents is an internal tool operated by SB AI Systems UK Ltd.</p>
      <p className="mt-4">
        This application connects to Instagram and TikTok on behalf of SB AI Systems&apos; own business
        accounts, using each platform&apos;s official API, to draft and publish social media content.
        Every post is generated by an AI content pipeline, automatically checked for compliance, and
        requires explicit human approval before it is published or sent to the connected account.
      </p>
      <p className="mt-4">
        This tool is used solely by authorized SB AI Systems personnel and is not offered as a
        public service. For questions, contact{" "}
        <a href="mailto:info@sbaisystems.co.uk" className="text-indigo-600 hover:underline">
          info@sbaisystems.co.uk
        </a>
        .
      </p>
    </main>
  );
}
